---
# tasks file for ec2-security-groups

- include: get-vpc-facts.yml
- include: create-empty-sg.yml
  when: aws_security_groups is defined
- include: populate-rules.yml
  when: aws_security_groups is defined
- include: tag-groups.yml
  when: aws_security_groups is defined
