---
# tasks file for ec2-security-groups

- import_tasks: get-vpc-facts.yml
- import_tasks: populate-rules.yml
  when: aws_security_groups is defined
- import_tasks: tag-groups.yml
  when: aws_security_groups is defined
